### ISSUE TITLE
MASTER: Szenarien

### ISSUE THREAD

**Issue by floAr** [floAr/WirVsVirus_Simulator#11]
Welche Szenarien wollen wir unterstützen, welche Effekte simulieren, welche Maßnahmen anbieten

**Comment by AnnKRink** [comment]
Einflussfaktoren auf Schwere des Krankheitsverlaufs bzw. Mortalität:

1. Kapazität Krankenhäuser (genauer gesagt: Intensivbetten und Beatmungsmaschinen)
	--> werden im Verlauf der Zeit mehr, da das Gesundheitssystem sich auf den Outbreak vorbereitet
	--> wenn ausgelastet, steigt Mortalität deutlich an

2. Anteil der Risikogruppe an der Bevölkerung 
Frage: Sollten wir hier wirklich nach Alter einteilen oder eher nach Risiko? Es gibt ja auch viele junge chronisch Kranke und genau das ist ein Problem in der Kommuikation, dass meist nur von den "Alten" gesprochen wird.

**Comment by AnnKRink** [comment]
Einflussfaktoren auf Verbreitung/Ansteckungsrate:

- Erweiterung der Stadt/des Lebensraums um
	- Schulen/Kitas (geöffnet vs. geschlossen)
	- Unternehmen (Arbeit vor Ort vs. Homeoffice)
	- Verschiedene Freizeitorte mit unterschiedlich hohem Ansteckungsrisiko (geöffnet vs. geschlossen bzw. nicht besucht)
		- Clubs/Parties (extrem hoch)
		- Sportverein/Fitnessstudie (hoch)
		- Park/öffentlicher Platz (ohne Gruppenbildung eher niedrig, mit Gruppenbildung hoch)
		- Supermärkte (stark besucht vs. normal besucht)
           -> hier ist natürlich noch viel mehr denkbar, aber das wären vielleicht erstmal gute Beispiele
- Anteil der Personen, die zu Hause bleiben

**Comment by AnnKRink** [comment]
Einflussfaktoren auf Verbreitung/Ansteckungsrate:

Einhaltung der Regeln
- Einhaltung der Hygieneregeln (Händewaschen, Husten/Niesen in Armbeuge)
- Einhaltung der "Abstandsregel" (1,5 - 2 Meter Abstand in der Öffentlichkeit) 
- Einhaltung des Social Distancing (zu Hause bleiben mit nur wenigen Personen im Haushalt)

Stufenweiser "Lockdown"
- Schließung von Freizeitangeboten
- Schließung von Schulen/Kitas
- Schließung von Unternehmen

**Comment by AnnKRink** [comment]
Nicht steuerbare Faktoren (würde ich also Prio 2 sehen - falls wir das nicht mehr schaffen, nehmen wir das textlich mit auf)
- Anteil alter Menschen an der Bevölkerung
- Anteil schwerer Verläufe der Krankheit

Maßnahmen auf individueller Ebene:
- Hygieneregeln ja/nein
- Abstandsregeln ja/nein
- Anteil Leute, die zu Hause bleiben: 20 % 50 % 80 %

Maßnahmen auf politischer Ebene:
- Kapazität der Krankenhäuser verdoppeln 
- Schulen/Kitas schließen
- Freizeitaktivitäten schließen
- Unternehmen schließen (zu Homeoffice verpflichten)
- Komplette Ausgangssperre (einzelne Personen müssen trotzdem raus, bestimmte Berufsgruppen, Arztbesuche etc.)

Maßnahmen auf medizinischer Ebene (würde ich also Prio 2 sehen - falls wir das nicht mehr schaffen, nehmen wir das textlich mit auf):
- Entwicklung eines Medikaments zur Heilung von 80 % der schweren Verläufe
- Entwicklung eines Impfstoffs, mit dem 80 % der Bevölkerung geimpft werden

Nicht steuerbare Faktoren (würde ich also Prio 2 sehen - falls wir das nicht mehr schaffen, nehmen wir das textlich mit auf)
- Anteil alter Menschen an der Bevölkerung
- Anteil schwerer Verläufe der Krankheit

**Comment by Sakati84** [comment]
- [x] Kapazitäten Krankenhäuser erhöhen
- [x] Verhaltensregeln -> ansteckungsrate -30%
- [x] Ausgangssperre -> Leute bleiben länger im Haus
- [x] Schulen schließen
- [x] Freizeitaktivitäten schließen
- [x] HomeOffice
- [x] Selbstquarantaine
- [x] Corona Tests
- [x] Social Distancing
