### ISSUE TITLE
Layout

### ISSUE THREAD

**Issue by floAr** [floAr/WirVsVirus_Simulator#15]
![image](https://user-images.githubusercontent.com/765387/77228204-057ba380-6b86-11ea-9093-0576dbf777e9.png)

Mal eine fixe idee zum groben layout

**Comment by AlpixTM** [comment]
Soll das Layout einigermaßen responsive sein?
Weil dann sollten wir uns von den fixen px Zahlen von Unity verabschieden. Ist es möglich, die Größe von dem Unity Player einfach in Abhängigkeit zur Fenstergröße zu setzen? Mit CSS?
Oder will das der Player nicht mitmachen?
