### ISSUE TITLE
MASTER: Frontend

### ISSUE THREAD

**Issue by floAr** [floAr/WirVsVirus_Simulator#25]
- [x] Group all content in center and grow from there (see img1)
- [x] Statistics should remove axis description for x (see img2)
- [x] Statistics should show legend below (see img2)
- [ ] Statistics should be a bit higher and also include other numerical statistics (4) (see img2)
- [ ] More 'muted' background. Could imagine trying white card for content and grey for background
- [ ] Credit and Logos
- [x] Toggles are not resetting on reload

![image](https://user-images.githubusercontent.com/765387/77244906-b3389200-6c1a-11ea-8c6e-571e25d550eb.png)

![image](https://user-images.githubusercontent.com/765387/77244944-06124980-6c1b-11ea-8317-b855c37ba42e.png)

**Comment by AlpixTM** [comment]
Toggles reseten sich jetzt
