### ISSUE TITLE
To Dos Frontend bis Abgabe

### ISSUE THREAD

**Issue by AnnKRink** [floAr/WirVsVirus_Simulator#26]
- [x] Einführungstext ganz oben
- [x] Hintergrundbild tauschen
- [x] Legende für Simulation einfügen
- [x] Korrektur Schalter Maßnahmen: Alles ja/nein außer "Menschen bleiben zu Hause". Hier Prozentzahlen mit Beschriftung --> welche Anteile lassen sich leicht programmieren?
- [x] interne und externe Verlinkungen in Texten ergänzen
- [x] Logo vom Hackathon einbinden: https://drive.google.com/open?id=1zzrE57uVZcqAXv6TN01PQqS7bfB0MuxD

**Comment by floAr** [comment]
Sortierung der Maßnahmen:

1. Menschen sollen Zuhause bleiben
2. Verhaltensregeln
3. Kapazitäten der KH
4. Homeoffice
5. Freizeitaktivtät schließen
6.  Schulen schließen
7. Umfassende Corona Tests

**Comment by AnnKRink** [comment]
Vorschläge Hintergrundbild:
https://www.pexels.com/de-de/collections/wirvsvirus-hintergrundbild-9jevj2x/ 

Neue Vorschläge:
https://adobe.ly/33A3JuG

**Comment by AlpixTM** [comment]
Hintergrundbild ist gewechselt

**Comment by AlpixTM** [comment]
Text ist da

**Comment by AlpixTM** [comment]
Alles gemacht :)!

Alles gemacht von den Tasks :)

**Comment by AnnKRink** [comment]
Super :) eine Kleinigkeit noch: Ich sehe in ein paar Texten noch Hinweise auf interne Links. Bei "Freizeitstätten schließen", "Schulschließungen", "Menschen bleiben zu Hause". Die müssten noch raus - oder seh ich ne ältere Version?

**Comment by AlpixTM** [comment]
Achso nein, mache ich raus! Super aufgepasst hatte ich vergessen!
