### ISSUE TITLE
Pitchvideo

### ISSUE THREAD

**Issue by AnnKRink** [floAr/WirVsVirus_Simulator#27]
Vorschlag Videoskript:
https://docs.google.com/document/d/1IE7UtR0KdnwjMabypImj3jM6yZQScU9WrcaCdaOU6Vo/edit?usp=sharing

Ich habe den Text ein paar mal durchgesprochen und gestoppt. Wir sollten bei ca. 1:30-1:45 landen, wenn man immer etwas Pause lässt, um das abgefilmte sehen zu können.

**Comment by AnnKRink** [comment]
Wer kann den Lead übernehmen für die technische Umsetzung?

**Comment by AnnKRink** [comment]
Update: Beschreibungstext etc. für Youtube ist vorbereitet. Wir können meinen Account nehmen, wenn niemand was dagegen hat.

**Comment by AlpixTM** [comment]
Können aber auch gerne meinen nehmen, hab 1100 Abos, muss aber nicht unbedingt sein.
Könnten damit aber paar Leute erreichen. Wie viele weiß ich nicht, weil ich seit 2 Jahren nichts mehr hochgeladen haben.. Habe ein junges Publikum, das weiß wie man einen PC bedient ^-^, aber nicht unbedingt IT Bezug hat (beruflich)

**Comment by AlpixTM** [comment]
Oder beide Kanäle?
Mein Kanal
[youtube.com/AlpixTM](https://www.youtube.com/c/AlpixTM)

**Comment by AnnKRink** [comment]
Dann lass auf jeden Fall deinen nehmen! Ich hab genau 0 Abonnenten :D

**Comment by Sakati84** [comment]
No Offense aber @AlpixTM  dein Kanal ist slightly NSFW. Lass mal ruhig den von @AnnKRink  nehmen. Bei so offiziellen Sachen weiss man ja nie...

**Comment by AlpixTM** [comment]
Gut machen wir!
Also mir ist es egal.

Finde schon, dass mein Kanal in Ordnung ist aber, wie du meinst :D

**Comment by AnnKRink** [comment]
Gut. Ich würde allerdings gern die Kommentarfunktion ausschalten - habe keine Lust, da die nächsten Tage irgendwas moderieren zu müssen. Wenn die Leute kommentieren wollen, sollen sie das auf Devpost machen, wo wir alle darauf reagieren könnten. Okay?

Und verbreiten sollten wir das Video erst aktiv, wenn wir das Projekt komplett abgegeben haben.

**Comment by AlpixTM** [comment]
Kommentare sind aber doch sehr schön eigentlich zu lesen und mit Kommentare wird man auch nicht von Algorithmus abgestraft und nicht schlechter gelistet.
Wenn du sonst nichts auf dem Account hoch lädst, könntest du auch meinen Account als Moderator in dem Kanal eintragen, dann kann ich löschen, falls da Bullshit kommt, denke ich aber tatsächlich nicht
